name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 6199/mecab-base-py37:latest
    steps:
    - uses: Checkout Project
    - name: actions/checkout@main

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black isort pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with isort and black
      run: |
        isort --check kokex
        black --check kokex

    - name: Test with pytest
      run: |
        bin/run_test.sh
