name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 6199/mecab-base-py37:latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@main

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: kokex version check
      run: echo '::set-output name=VERSION::$(python -c 'import kokex; print(kokex.__version__)')'
      id: kokex-version-check

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: docker/Dockerfile
        push: true
        tags: 6199/kokex-test:${{ steps.kokex-version-check.outputs.VERSION }}
